from django.conf.urls import url
from ReviewBeforeYouBuy import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^Welcome/$', views.Welcome),
    url(r'^Mobile/$', views.Mobiles),
	url(r'^Laptop/$', views.Laptops),
	url(r'^Camera/$', views.Camera),
	url(r'^Admin/$', views.Admin),
	url(r'^Computer_Hardware/$', views.Computer_Hardwares),
	url(r'^Electronic_Accessories/$', views.Electronic_Accessories),
	url(r'^Forgot_password/$', views.Forgot_password),
	url(r'^Login/$', views.Login),
	url(r'^New_Password/$', views.New_Password),
	url(r'^OTP_verify/$', views.OTP_verify),
	url(r'^Registration/$', views.Registration),
	url(r'^Smart_Watch/$', views.Smart_Watch),
	url(r'^Contact/$',views.Contact),
	url(r'^Show_Content/$',views.Show_Content),
	url(r'^Register/$',views.Register),
	url(r'^Logging/$',views.Logging),
	url(r'^Generate_Otp/$',views.Generate_Otp),
	url(r'^Verification_OTP/$',views.Verification_OTP),
	url(r'^Change_Password/$',views.Change_Password),
	url(r'^Logout/$',views.Logout),
	url(r'^Notified/$',views.Notified),
	url(r'^M_Show_Content/$',views.M_Show_Content),
	url(r'^L_Show_Content/$',views.L_Show_Content),
	url(r'^C_Show_Content/$',views.C_Show_Content),
	url(r'^S_Show_Content/$',views.S_Show_Content),
	url(r'^E_Show_Content/$',views.E_Show_Content),
	url(r'^H_Show_Content/$',views.H_Show_Content),
	url(r'^M_INFO/$',views.M_INFO),
	url(r'^L_INFO/$',views.L_INFO),
	url(r'^C_INFO/$',views.C_INFO),
	url(r'^S_INFO/$',views.S_INFO),
	url(r'^H_INFO/$',views.H_INFO),
	url(r'^E_INFO/$',views.E_INFO),
	url(r'^M_Save_FeedBack/$',views.M_Save_FeedBack),
	url(r'^L_Save_FeedBack/$',views.L_Save_FeedBack),
	url(r'^C_Save_FeedBack/$',views.C_Save_FeedBack),
	url(r'^E_Save_FeedBack/$',views.E_Save_FeedBack),
	url(r'^H_Save_FeedBack/$',views.H_Save_FeedBack),
	url(r'^S_Save_FeedBack/$',views.S_Save_FeedBack),
	url(r'^Add_Product/$',views.Add_Product),

]
