# Generated by Django 2.1.7 on 2019-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBeforeYouBuy', '0002_cameras_computer_hardware_electronic_accessory_laptop_mobile_smart_watches_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras_Feedback',
            fields=[
                ('c_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_feedback', models.CharField(max_length=100)),
                ('c_user', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Cameras')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Hardware_Feedback',
            fields=[
                ('c_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_feedback', models.CharField(max_length=100)),
                ('c_user', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Computer_Hardware')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic_Accessory_Feedback',
            fields=[
                ('e_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_feedback', models.CharField(max_length=100)),
                ('e_user', models.CharField(max_length=50)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Electronic_Accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_Feedback',
            fields=[
                ('l_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_feedback', models.CharField(max_length=100)),
                ('l_user', models.CharField(max_length=50)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Laptop')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Feedback',
            fields=[
                ('m_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_feedback', models.CharField(max_length=100)),
                ('m_user', models.CharField(max_length=50)),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Smart_Watches_Feedback',
            fields=[
                ('s_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_feedback', models.CharField(max_length=100)),
                ('s_user', models.CharField(max_length=50)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewBeforeYouBuy.Smart_Watches')),
            ],
        ),
    ]
