# Generated by Django 2.1.7 on 2019-04-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBeforeYouBuy', '0005_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='c_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='c_photo_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='computer_hardware',
            name='h_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='computer_hardware',
            name='h_photo_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='electronic_accessory',
            name='e_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='electronic_accessory',
            name='e_photo_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='l_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='l_photo_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='m_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='m_photo_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='smart_watches',
            name='s_content_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='smart_watches',
            name='s_photo_link',
            field=models.CharField(max_length=300),
        ),
    ]
