# Generated by Django 2.1.7 on 2019-04-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBeforeYouBuy', '0006_auto_20190407_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras_feedback',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='computer_hardware_feedback',
            name='c_user',
        ),
        migrations.RemoveField(
            model_name='electronic_accessory_feedback',
            name='e_user',
        ),
        migrations.RemoveField(
            model_name='mobile_feedback',
            name='m_user',
        ),
        migrations.RemoveField(
            model_name='smart_watches_feedback',
            name='s_user',
        ),
    ]
