# Generated by Django 2.1.7 on 2019-04-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBeforeYouBuy', '0007_auto_20190408_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameras_feedback',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='computer_hardware_feedback',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='electronic_accessory_feedback',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='laptop_feedback',
            name='l_id',
        ),
        migrations.RemoveField(
            model_name='laptop_feedback',
            name='l_user',
        ),
        migrations.RemoveField(
            model_name='mobile_feedback',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='smart_watches_feedback',
            name='s_id',
        ),
    ]
